version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
    depends_on:
      - db
    links:
      - redis_db

  postgres_db:
    container_name: postgres_db
    image: postgres:14.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis_db:
    container_name: redis_db
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

# to do celery containers

volumes:
  postgres-data:
  redis-data:
